### PR TITLE
Fix SearchRequest.Type being ignored

### PR DESCRIPTION
**Pull request by pettys**
Thanks for building and sharing this library! I noticed SearchRequest.Type wasn't filtering the results, and I think this might be the problem. Hope it's an easy pull!

### CODE REVIEW

**Comment by Cobster** [comment]
Oops overlooked that! Thanks for the PR @pettys.  I'll get this merged and push a new package out to Nuget later today.

**Comment by Cobster** [comment]
@pettys This has been published to NuGet as v0.7.1, thanks again!  Cheers! 🍻

**Comment by Cobster** [comment]
It may take up to an hour to be available.

**Comment by pettys** [comment]
I updated the package and it's working great. Thanks for the quick turn-around!

**Pull request merged**
